Insert into admin values('admin','1234');

insert into customer values('B5917389','opal','0988188216');
insert into customer values('B5917402','minny','0877177214');
insert into customer values('B5917419','ployly','0202122242');
insert into customer values('B5917426','graph','0966166212');
insert into customer values('B5917433','sunny','0944444444');
insert into customer values('B5917440','armmy','0888067837');
insert into customer values('B5917471','aony','0861411523');
insert into customer values('B5917488','bassy','0881122334');
insert into customer values('B5900909','ploysuzy','0822122242');
insert into customer values('B5900947','wowwy','0123456789');
insert into customer values('B5909964','whanny','0313326339');

insert into information values('S01','8 Bisto','Korat','044-248888','International Food');
insert into information values('S02','Suzette','Korat','044-322283','Pizza');
insert into information values('S03','Jade Cuisine','Korat','087-6442693','Thai Food');
insert into information values('S04','Shabu Indy','Korat','093-1374536','Shabu');
insert into information values('S05','Starbucks','Korat','084-3569538','Drink');
insert into information values('S06','Krua Plern Pung','Korat','088-5946636','Thai Food');
insert into information values('S07','Dee Den Icecream','Korat','0987758939','Icecream');
insert into information values('S08','Da De Bar On Festival','Korat','087-9878900','Thai Food');
insert into information values('S09','Krua Khao Yai','Korat','086-8659263','Thai Food');
insert into information values('S10','Laapnua','Korat','084-3569689','Thai Food');

INSERT INTO reservation VALUES (reservation_seq.nextval,'02-02-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'03-03-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'02-04-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'05-03-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'07-09-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'03-01-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'04-07-2018');
INSERT INTO reservation VALUES (reservation_seq.nextval,'01-03-2018');

Insert into tableA values('Empty','TB1','S01');
Insert into tableA values('Empty','TB2','S01');
Insert into tableA values('Empty','TB3','S01');
Insert into tableA values('Empty','TB4','S01');
Insert into tableA values('Empty','TB5','S01');
Insert into tableA values('Full','TB6','S01');
Insert into tableA values('Full','TB7','S01');
Insert into tableA values('Full','TB8','S01');
Insert into tableA values('Full','TB9','S01');
Insert into tableA values('Full','TB10','S01');

Insert into tableA values('Empty','TA1','S02');
Insert into tableA values('Empty','TA2','S02');
Insert into tableA values('Empty','TA3','S02');
Insert into tableA values('Empty','TA4','S02');
Insert into tableA values('Empty','TA5','S02');
Insert into tableA values('Full','TA6','S02');
Insert into tableA values('Full','TA7','S02');
Insert into tableA values('Full','TA8','S02');
Insert into tableA values('Full','TA9','S02');
Insert into tableA values('Full','TA10','S02');

Insert into tableA values('Empty','TC1','S03');
Insert into tableA values('Empty','TC2','S03');
Insert into tableA values('Empty','TC3','S03');
Insert into tableA values('Empty','TC4','S03');
Insert into tableA values('Empty','TC5','S03');
Insert into tableA values('Full','TC6','S03');
Insert into tableA values('Full','TC7','S03');
Insert into tableA values('Full','TC8','S03');
Insert into tableA values('Full','TC9','S03');
Insert into tableA values('Full','TC10','S03');

Insert into tableA values('Empty','TD1','S04');
Insert into tableA values('Empty','TD2','S04');
Insert into tableA values('Empty','TD3','S04');
Insert into tableA values('Empty','TD4','S04');
Insert into tableA values('Empty','TD5','S04');
Insert into tableA values('Full','TD6','S04');
Insert into tableA values('Full','TD7','S04');
Insert into tableA values('Full','TD8','S04');
Insert into tableA values('Full','TD9','S04');
Insert into tableA values('Full','TD10','S04');

Insert into tableA values('Empty','TE1','S05');
Insert into tableA values('Empty','TE2','S05');
Insert into tableA values('Empty','TE3','S05');
Insert into tableA values('Empty','TE4','S05');
Insert into tableA values('Empty','TE5','S05');
Insert into tableA values('Full','TE6','S05');
Insert into tableA values('Full','TE7','S05');
Insert into tableA values('Full','TE8','S05');
Insert into tableA values('Full','TE9','S05');
Insert into tableA values('Full','TE10','S05');

Insert into tableA values('Empty','TF1','S06');
Insert into tableA values('Empty','TF2','S06');
Insert into tableA values('Empty','TF3','S06');
Insert into tableA values('Empty','TF4','S06');
Insert into tableA values('Empty','TF5','S06');
Insert into tableA values('Full','TF6','S06');
Insert into tableA values('Full','TF7','S06');
Insert into tableA values('Full','TF8','S06');
Insert into tableA values('Full','TF9','S06');
Insert into tableA values('Full','TF10','S06');

Insert into tableA values('Empty','TG1','S07');
Insert into tableA values('Empty','TG2','S07');
Insert into tableA values('Empty','TG3','S07');
Insert into tableA values('Empty','TG4','S07');
Insert into tableA values('Empty','TG5','S07');
Insert into tableA values('Full','TG6','S07');
Insert into tableA values('Full','TG7','S07');
Insert into tableA values('Full','TG8','S07');
Insert into tableA values('Full','TG9','S07');
Insert into tableA values('Full','TG10','S07');

Insert into tableA values('Empty','TH1','S08');
Insert into tableA values('Empty','TH2','S08');
Insert into tableA values('Empty','TH3','S08');
Insert into tableA values('Empty','TH4','S08');
Insert into tableA values('Empty','TH5','S08');
Insert into tableA values('Full','TH6','S08');
Insert into tableA values('Full','TH7','S08');
Insert into tableA values('Full','TH8','S08');
Insert into tableA values('Full','TH9','S08');
Insert into tableA values('Full','TH10','S08');

Insert into tableA values('Empty','TI1','S09');
Insert into tableA values('Empty','TI2','S09');
Insert into tableA values('Empty','TI3','S09');
Insert into tableA values('Empty','TI4','S09');
Insert into tableA values('Empty','TI5','S09');
Insert into tableA values('Full','TI6','S09');
Insert into tableA values('Full','TI7','S09');
Insert into tableA values('Full','TI8','S09');
Insert into tableA values('Full','TI9','S09');
Insert into tableA values('Full','TI10','S09');

Insert into tableA values('Empty','TJ1','S10');
Insert into tableA values('Empty','TJ2','S10');
Insert into tableA values('Empty','TJ3','S10');
Insert into tableA values('Empty','TJ4','S10');
Insert into tableA values('Empty','TJ5','S10');
Insert into tableA values('Full','TJ6','S10');
Insert into tableA values('Full','TJ7','S10');
Insert into tableA values('Full','TJ8','S10');
Insert into tableA values('Full','TJ9','S10');
Insert into tableA values('Full','TJ10','S10');
